name: Django CI

on:
  push:
    branches: [ "main" ]
    paths:
      - projects/AlphaVantage/webBackend/**
  pull_request:
    branches: [ "main" ]
    paths:
      - projects/AlphaVantage/webBackend/**

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      working-directory: projects/AlphaVantage
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: View pwd
      run: pwd
    - name: Run Tests
      working-directory: projects/AlphaVantage/webBackend/
      run: |
        python manage.py test
